dishes/urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import *
from .views_api import *
from rest_framework import routers, serializers, viewsets

router = routers.DefaultRouter()
router.register(r'dishes', DishViewSet)
# router.register(r'dishes(?P<name>a-z0-9+)/?$',
# DishViewSet.as_view().get_queryset, basename="Filter")
router.register(r'order', OrderViewSet)
# router.register(r'^dishes/(?P<name>.+)/$',
# DishApiList.get_queryset(), basename="125")

urlpatterns = [
    path('dishes/', InstanceDishView.as_view()),
    # path('', StartView.as_view(), name='start_page'),
    path('ingredients/', IngredientView.as_view()),
    path('drinks/', DrinkView.as_view()),
    path('dishes/list', DishViewList.as_view(), name='list_of_dish'),
    path('ingredients/list', IngredientViewList.as_view()),
    path('ingredients/new/', MakeIngredient.as_view(), name='ingredient_form'),
    path('drinks/new/', MakeDrink.as_view(), name='drinks_form'),
    path('dishes/new/', MakeDishes.as_view(), name='dishes_new'),
    path('dishes/add/', AddDish.as_view(), name='add_dish_to_order'),
    path('price/', CreateNewPrice.as_view(), name='new price'),
    path('sort/', MakeSort.as_view(), name='make sort'),
    path('drinks/<int:pk>/edit/', UpdateDrink.as_view(), name='update_drink'),
    path('ingredients/<int:pk>/edit/',
         UpdateIngredient.as_view(), name='update_ingredient'),
    path('dishes/<int:pk>/edit/', UpdateDish.as_view(), name='update_dish'),
    path('dishes/<int:pk>/', DishDetailView.as_view(), name='dish'),
    path('drinks/<int:pk>/', DrinkDetailView.as_view(), name='drink'),
    path('rest_api/', include(router.urls)),
    path('api/dishes_list/', DishesApiView.as_view(), name='dishes_list_api'),
    path('api/order/', OrderApiView.as_view(), name='order_api'),
    path('api/dish/add_to_order/',
         DishesAddOrderApiView.as_view(), name='dish_add_to_order'),
    # path('api/', include('dishes.urls')),
    # path('rest_api/ ^dishes/(?P<name>a-z0-9+)/?$',
    # DishApiList.as_view(), name='dish_filter'),
    # path('api/dishes/(?P<name>.+)/$',
    # DishApiList.as_view(), name='dish_api_list')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page
from project.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', TemplateView.as_view(template_name="index.html")),
    path('', cache_page(60*10)(HomeView.as_view(template_name="home.html"))),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
    path('', include('dishes.urls')),
    path('', include('order.urls')),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += staticfiles_urlpatterns()

urls.py
from django.conf.urls import url, include
from django.urls import path
from .views import *
from  .views_api import *
from rest_framework import routers, serializers, viewsets

router = routers.DefaultRouter()
router.register(r'dishes', DishViewSet)

urlpatterns = [
    path('dishes/', InstanceDishView.as_view()),
    # path('', StartView.as_view(), name='start_page'),
    path('ingredients/', IngredientView.as_view()),
    path('drinks/', DrinkView.as_view()),
    path('dishes/list', DishViewList.as_view(), name='list_of_dish'),
    path('ingredients/list', IngredientViewList.as_view()),
    path('ingredients/new/', MakeIngredient.as_view(), name='ingredient_form'),
    path('drinks/new/', MakeDrink.as_view(), name='drinks_form'),
    path('dishes/new/', MakeDishes.as_view(), name='dishes_new'),
    path('dishes/add/', AddDish.as_view(), name='add_dish_to_order'),
    path('price/', CreateNewPrice.as_view(), name='new price'),
    path('sort/', MakeSort.as_view(), name='make sort'),
    path('drinks/<int:pk>/edit/', UpdateDrink.as_view(), name='update_drink'),
    path('ingredients/<int:pk>/edit/',
         UpdateIngredient.as_view(), name='update_ingredient'),
    path('dishes/<int:pk>/edit/', UpdateDish.as_view(), name='update_dish'),
    path('dishes/<int:pk>/', DishDetailView.as_view(), name='dish'),
    path('drinks/<int:pk>/', DrinkDetailView.as_view(), name='drink'),
    path('api/', include(router.urls)),
    path('api/dishes_list/', DishesApiView.as_view(), name='dishes_list_api'),
    path('api/order/', OrderApiView.as_view(), name='order_api'),
    path('api/dish/add_to_order/', DishesAddOrderApiView.as_view(), name='dish_add_to_order'),
    # path('api/', include('dishes.urls')),

]

dishes/models.py
from django.db import models


class BaseItem(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    class Meta:
        abstract = True


class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    is_vegan = models.BooleanField(default=False)
    is_meat = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ингредиент'
        verbose_name_plural = 'Ингредиенты'


class DishCategory(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Вид еды'
        verbose_name_plural = 'Виды еды'


class Dish(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    discount = models.IntegerField(blank=True, null=True, default=0)
    category = models.ForeignKey(
        DishCategory,
        blank=True, null=True,
        default=None, on_delete=models.SET_NULL
    )
    short_description = models.TextField(blank=True, null=True, default=None)
    description = models.TextField(blank=True, null=True, default=None)

    # ingredients = models.ManyToManyField(Ingredient, blank=True)

    def __str__(self):
        return self.name

    def create_instance_dish(self, count):
        return InstanceDish.objects.create(
            name=self.name,
            price=self.price,
            dish_template=self,
            count=count
        )

    def get_serialize_dishes(self):
        return {
            "id": self.id,
            "name": self.name,
            "price": self.price,
            "description": self.description,
        }

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'


class Drink(BaseItem):
    short_description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    discount = models.IntegerField(blank=True, null=True, default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Напиток'
        verbose_name_plural = 'Напитки'


class ChangePrice(models.Model):
    change_price = models.DecimalField(
        max_digits=9, decimal_places=2, default=0
    )


class SortDish(models.Model):
    FILTER_TYPES = (
        ('price', 'price по возрастанию'),
        ('-price', 'price по убыванию'),
        ('name', 'name по возрастанию'),
        ('-name', 'name убыванию'),
    )
    sort = models.CharField(
        max_length=15, choices=FILTER_TYPES, default='price +'
    )


class InstanceDish(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    count = models.PositiveSmallIntegerField(default=1)
    dish_template = models.ForeignKey(
        Dish, related_name="dish_templates", blank=True, null=True,
        on_delete=models.SET_NULL
    )

    def __str__(self):
        return 'name: {}, price {},  full_price: {}  '\
            .format(self.name, str(self.price), str(self.price * self.count))

    def all_price_dish(self):
        all_price = self.price * self.count
        return all_price


class DishImage(models.Model):
    dish = models.ForeignKey(
        Dish,
        blank=True, null=True,
        default=None, on_delete=models.SET_NULL
    )
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to="dishes_images/")

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография еды'
        verbose_name_plural = 'Фотографии еды'


class DrinkImage(models.Model):
    drink = models.ForeignKey(
        Drink,
        blank=True, null=True,
        default=None, on_delete=models.SET_NULL
    )
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(upload_to="drink_images/")

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография напитка'
        verbose_name_plural = 'Фотографии напитков'

dishes/forms.py
from django.forms import ModelForm, Form
from dishes.models import Ingredient, Drink, Dish, SortDish, InstanceDish
from django import forms


class IngredientForm(ModelForm):
    name = forms.CharField(required=True, max_length=15)
    price = forms.DecimalField(required=True, max_digits=2)

    class Meta:
        model = Ingredient
        fields = ['name', 'is_vegan', 'is_meat', 'price']


class DrinkForm(ModelForm):
    class Meta:
        model = Drink
        fields = ['name', 'price']


class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = ['name', 'price']


class ChangePriceForm(Form):
    change_price = forms.DecimalField(required=True, max_digits=2)


class SortForm(ModelForm):
    class Meta:
        model = SortDish
        fields = ['sort']


class AddDishForm(Form):
    dish_id = forms.IntegerField()
    count = forms.IntegerField()


class CountForm(Form):
    count = forms.IntegerField()

dishes/templates/dishes/dish.html
{% extends 'base.html' %}
{% load static %}
{% block main %}


<div class="dish-drink-container">
    <div class="row">
        <div class="col-lg-6">
            {% for image_item in dish.dishimage_set.all %}
            <div class="dish-image-item">
               <img src="{{image_item.image.url}}" class="img-responsive">
            </div>
             {%endfor%}
        </div>
        <div class="col-lg-6">
            <h1 class="text-center">
                {{dish.name}}
            </h1>
            <div class="">
                <p>
                    Цена:  {{dish.price}}
                </p>
            </div>
            <div class="">
                {{dish.description}}
            </div>
        <br/>
         <br/>
             <div>
                 <br/>
                 <br/>
                 <form id="form_dish" method="POST"  class="form-inline" class="post-form" action = "/dishes/add/">{% csrf_token %}
                     <div class="form-group">
                         <input type="text"  value = {{dish.id}} hidden name = "dish_id">
                         <label for="number">Количество</label>
                         <input type="number"  name = "count" class="form-control">
                     </div>
                     <div class="form-group">
        <button type="submit" class="btn btn-success">
            Добавить в корзину
        </button>
                         </div>
        </form>
             </div>
        </div>
    </div>

</div>

{% endblock %}

dishes/templates/dishes/dishes_add_form.html
<!DOCTYPE html>
{%extends "base.html"%}
{%block main%}
<html lang="ru">
<h1>Dishes__add</h1>
<div>
             {% for dish in list_dish %}
    <li>{{ dish.name }}  -  цена {{ dish.price }} грн. </li>
    <form method="POST"  class="post-form" action = "/dishes/add/">{% csrf_token %}
    <input type="text"  value = {{dish.id}} hidden name = "dish_id">
    <label for="number">Количество блюд</label>
    <input type="number"  name = "count">
        <button type="submit" class="save btn btn-default">Добавить в корзину</button>
        </form>
    {% endfor %}
    <form action = '/order/' method="GET">
    <input type = "submit"  value  = "Заказ">

</form>

</div>
{{order}}
<a href  = "/ingredients"> Ingredient</a>
<a href  = "/dishes"> Dishes</a>
<a href  = "/drinks"> Drinks</a>
<a href  = '/'> Start </a>
</html>
{%endblock%}

dishes/templates/dishes/dishes_form.html
<!DOCTYPE html>
{%extends "base.html"%}
{%block main%}
<html lang="ru">
<h1>Dishes</h1>
<ul>
    <form method="POST" class="post-form">{% csrf_token %}
    {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

</ul>
<a href  = "/ingredients"> Ingredient</a>
<a href  = "/dishes"> Dishes</a>
<a href  = "/drinks"> Drinks</a>
<a href  = '/'> Start </a>
</html>
{%endblock%}

dishes/templates/dishes/dishes_list.html
{%extends "base.html"%}
{%block main%}
<h1>DISHES</h1>
<h2>количество блюд {{count_dish}}</h2>
<h3>{{ my_var|lower }}</h3>
<h2> 1) Values :{{list_dish1}}</h2>
<h2> 2) Values_list :{{list_dish2}}</h2>
<h3> цена больше 200{{filter200}}</h3>
<h3> цена больше 50 {{filter50}}</h3>
{% block head_title %}Dishes List{% endblock %}
<hr>
<em><a href  = "/dishes/new"> ДОБАВИТЬ БЛЮДО</a></em></br>
<hr>
<ol>
{% for dish in object_list %}
    <li>{{ dish.name | lower}} ---- {{ dish.price }}</li>
    <td><a href="{{dish.id}}/edit/">Изменить</a> </td>
{% empty %}
    <li>No  yet.</li>
    {% endfor %}
</ol>
 <a href  = "/dishes"> Dishes view</a></br>

<strong> <a href  = "/price"> Изменить цену</a></strong></br>
<strong> <a href  = "/sort"> Cортировка </a></strong></br>
<p>
    <hr>
    {% if object_list %}
<strong>Количество блюд: {{ object_list|length }}</strong>
    {% else %}
    Нет еще блюд.
{% endif %}
</p>

{%endblock%}

dishes/templates/dishes/drink.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<div class="dish-drink-container">
    <div class="row">
        <div class="col-lg-6">
            {% for image_item in drink.drinkimage_set.all %}
                <img src="{{image_item.image.url}}" class="img-responsive">
             {%endfor%}
        </div>
        <div class="col-lg-6">
            <h1 class="text-center">
                {{drink.name}}
            </h1>
            <div class="">
                <p>
                    Цена:  {{drink.price}}
                </p>
            </div>
            <div class="">
                {{drink.short_description}}
            </div>
            <br/>
         <br/>
             <div>
                 <form id="form_dish" method="POST"  class="form-inline" class="post-form" action = "/dishes/add/">{% csrf_token %}
                     <div class="form-group">
                         <input type="text"  value = {{drink.id}} hidden name = "drink_id">
                         <label for="number">Количество</label>
                         <input type="number"  name = "count" class="form-control">
                     </div>
                     <div class="form-group">
        <button type="submit" class="btn btn-success">
            Добавить в корзину
        </button>
                         </div>
        </form>
             </div>
        </div>
    </div>
</div>


{% endblock %}

dishes/templates/dishes/drinks.html
{%extends "base.html"%}
{%block main%}
<h1>DRINKS</h1>
{% block head_title %}Drinks{% endblock %}
<h3>{{ my_var|upper }}</h3>
<hr>
<strong><em><a href  = "/drinks/new"> ДОБАВИТЬ</a></em></strong>
 <a href  = "/drinks"> Список напитков</a>
{%endblock%}

dishes/templates/dishes/drinks_form.html
<!DOCTYPE html>
{%extends "base.html"%}
{%block main%}
<html lang="ru">
<h1>Drinks</h1>
<ul>
    <form method="POST" class="post-form">{% csrf_token %}
    {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

</ul>
<a href  = "/ingredients"> Ingredient</a>
<a href  = "/dishes"> Dishes</a>
<a href  = "/drinks"> Drinks</a>
<a href  = '/'> Start </a>
</html>
{%endblock%}

dishes/templates/dishes/ingredient.html
{%extends "base.html"%}
{%block main%}
<h1>INGREDIENTS</h1>
{% block head_title %}Ingredients{% endblock %}

    <ul>
    <a href  = "/ingredients/list"> Список ингредиентов</a>
        <strong><em> <a href  = "/ingredients/new"> ДОБАВИТЬ</a></em></strong>
    </ul>
{%endblock%}

dishes/templates/dishes/ingredient_list.html
{%extends "base.html"%}
{%block main%}
<h1>INGREDIENTS</h1>
<h3>{{ my_var|title }}</h3>
{% block head_title %}Ingredients List{% endblock %}
<hr>
<ul>
{% for ingredient in object_list %}
    <li>{{ ingredient.name|upper }} ---- {{ ingredient.price }}</li>
    <td><a href="{{ingredient.id}}/edit/">Изменить</a> </td>
{% empty %}
    <li>No  yet.</li>
{% endfor %}
</ul>
<em><a href  = "/ingredients/new"> ДОБАВИТЬ</a></em>

<p>
    <hr>
    {% if object_list %}
<strong> Количество ингредиентов: {{ object_list|length }}</strong>
    {% else %}
    Не заполнены ингредиенты.
{% endif %}
</p>

{%endblock%}

dishes/templates/dishes/ingredients.html
<!DOCTYPE html>
{%extends "base.html"%}
{%block main%}
<html lang="ru">
<h1>New Ingredient</h1>
<ul>
    <form method="POST" class="post-form">{% csrf_token %}
    {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

</ul>
<a href  = "/ingredients"> Ingredient</a>
<a href  = "/dishes"> Dishes</a>
<a href  = "/drinks"> Drinks</a>
<a href  = '/'> Start </a>
</html>
{%endblock%}

dishes/templates/dishes/price_form.html
<!DOCTYPE html>
{%extends "base.html"%}
{%block main%}
<html lang="ru">
<h1>Price</h1>
<ul>
    <form method="POST" class="post-form">{% csrf_token %}
    {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

</ul>
<a href  = "/price/update_price"> Повысить цену</a>
<a href  = '/'> Start </a>
</html>
{%endblock%}

dishes/templates/dishes/price_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

dishes/templates/dishes/sort.html
<!DOCTYPE html>
{%extends "base.html"%}
{%block main%}
<html lang="ru">
<h1>SortDish</h1>
<ul>
    <form method="POST" class="post-form">{% csrf_token %}
    {{form.as_p}}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

</ul>
<a href  = "/ingredients"> Ingredient</a>
<a href  = "/dishes"> Dishes</a>
<a href  = "/drinks"> Drinks</a>
<a href  = '/'> Start </a>
</html>
{%endblock%}

dishes/templates/dishes/start.html
<!DOCTYPE html>
{%extends "base.html"%}
{%block main%}
<html lang="ru">
<h1>PIZZA</h1>

<a href  = "/ingredients/list"> Ingredient</a>
<a href  = "/dishes"> Dishes</a>
<a href  = "/drinks"> Drinks</a>
</html>
{%endblock%}